ARG PHP_VERSION
FROM php:${PHP_VERSION}-cli

RUN ls -1 /etc/*release | xargs -i sh -c 'echo {} && cat {}'

RUN apt-get -qq update \
    && apt-get -qq -y --no-install-recommends install \
        git \
        libpq-dev \
        libzip-dev \
        logrotate \
        procps \
        rsyslog

RUN docker-php-ext-install \
        mysqli \
        pgsql \
        zip

# OPcache is built into PHP core since 8.5
RUN if [ "$(php -r 'echo PHP_VERSION_ID;')" -lt 80500 ]; then docker-php-ext-install opcache; fi

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /

ENTRYPOINT exec /read_only_repo_root/tools/test/component/docker_entrypoint.sh
