---

name: audit-php-deps

on:
  workflow_call: ~
  workflow_dispatch: ~

permissions:
  contents: read

jobs:
  audit-php-deps:
    name: audit-php-deps
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      COMPOSER_ALLOW_SUPERUSER: 1
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Run composer audit for production dependencies
        run: |
          source ./tools/read_properties.sh
          read_properties project.properties PROJECT_PROPERTIES
          PHP_VERSIONS=${PROJECT_PROPERTIES_SUPPORTED_PHP_VERSIONS//[()]/}
          ./tools/build/audit_PHP_deps.sh --php_versions "${PHP_VERSIONS}"
